spring:
  server:
      port: 8081
  datasource: 
    url: jdbc:h2:mem:testdb
    user: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    database-plataform: org.hibernate.dialect.H2Dialect
    properties.hibernate.show_sql: true
    properties.hibernate.format_sql: true
  h2: 
    console:
      enabled: true
      path: /h2
  springdoc:
    api-docs:
      path:/api-docs
